# Generated by Django 5.1.2 on 2024-10-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='services.category'),
        ),
    ]
