# Generated by Django 5.1.2 on 2024-11-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_featured_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
