# Generated by Django 5.1.2 on 2024-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
