# Generated by Django 5.1.2 on 2024-10-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_quantity_cartitem_quantity'),
        ('services', '0003_service_is_featured_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.service'),
        ),
    ]
