# Generated by Django 5.1.2 on 2024-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_session_key_cart_cart_id_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='session_key',
        ),
    ]
