# Generated by Django 5.1.2 on 2024-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cartitem_user_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
