# Generated by Django 5.1.2 on 2024-11-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_total_amount_remove_order_updated_at_and_more'),
        ('services', '0004_service_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
