# Generated by Django 5.1.2 on 2024-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='Dhaka', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='road_number',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ward_number',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
