# Generated by Django 5.1.2 on 2024-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_contact_name_order_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'Bkash'), ('credit', 'Credit Card')], default='cash', max_length=20),
        ),
    ]
